//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRHub.DriverImageUploader {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DriverImageUploader.WebUploadFileSoap")]
    public interface WebUploadFileSoap {
        
        // CODEGEN: Generating message contract since element name f from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        SignalRHub.DriverImageUploader.UploadFileResponse UploadFile(SignalRHub.DriverImageUploader.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<SignalRHub.DriverImageUploader.UploadFileResponse> UploadFileAsync(SignalRHub.DriverImageUploader.UploadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public SignalRHub.DriverImageUploader.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(SignalRHub.DriverImageUploader.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] f;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LinkId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DriverNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ClientId;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(byte[] f, string fileName, string LinkId, string DriverNo, string ClientId) {
            this.f = f;
            this.fileName = fileName;
            this.LinkId = LinkId;
            this.DriverNo = DriverNo;
            this.ClientId = ClientId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public SignalRHub.DriverImageUploader.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(SignalRHub.DriverImageUploader.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebUploadFileSoapChannel : SignalRHub.DriverImageUploader.WebUploadFileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebUploadFileSoapClient : System.ServiceModel.ClientBase<SignalRHub.DriverImageUploader.WebUploadFileSoap>, SignalRHub.DriverImageUploader.WebUploadFileSoap {
        
        public WebUploadFileSoapClient() {
        }
        
        public WebUploadFileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebUploadFileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebUploadFileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebUploadFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SignalRHub.DriverImageUploader.UploadFileResponse SignalRHub.DriverImageUploader.WebUploadFileSoap.UploadFile(SignalRHub.DriverImageUploader.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] f, string fileName, string LinkId, string DriverNo, string ClientId) {
            SignalRHub.DriverImageUploader.UploadFileRequest inValue = new SignalRHub.DriverImageUploader.UploadFileRequest();
            inValue.Body = new SignalRHub.DriverImageUploader.UploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            inValue.Body.LinkId = LinkId;
            inValue.Body.DriverNo = DriverNo;
            inValue.Body.ClientId = ClientId;
            SignalRHub.DriverImageUploader.UploadFileResponse retVal = ((SignalRHub.DriverImageUploader.WebUploadFileSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignalRHub.DriverImageUploader.UploadFileResponse> SignalRHub.DriverImageUploader.WebUploadFileSoap.UploadFileAsync(SignalRHub.DriverImageUploader.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignalRHub.DriverImageUploader.UploadFileResponse> UploadFileAsync(byte[] f, string fileName, string LinkId, string DriverNo, string ClientId) {
            SignalRHub.DriverImageUploader.UploadFileRequest inValue = new SignalRHub.DriverImageUploader.UploadFileRequest();
            inValue.Body = new SignalRHub.DriverImageUploader.UploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            inValue.Body.LinkId = LinkId;
            inValue.Body.DriverNo = DriverNo;
            inValue.Body.ClientId = ClientId;
            return ((SignalRHub.DriverImageUploader.WebUploadFileSoap)(this)).UploadFileAsync(inValue);
        }
    }
}
